version: '3'

services:
  postgres_test:
    image: postgres:13.1-alpine
    restart: always
    environment:
      POSTGRES_USER: wealcome
      POSTGRES_PASSWORD: wealcome
      POSTGRES_DB: ubertop_db_test
    ports:
      - 5437:5432
    volumes:
      - ./docker-postgresql-data-for-test:/var/lib/postgresql/data
      - ./migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
